### ISSUE TITLE
latest V3 SDK is not working with Next.js due to polyfills

### ISSUE THREAD

**Issue by marcustut** [bcnmy/mexa-sdk#140]
**Describe the bug**
I've recently upgraded from V2 to V3 for my Next.js app and the app does not start.

**To Reproduce**
Create a nextjs 12 and use V3 Biconomy SDK [StackBlitz reproduction](https://stackblitz.com/edit/nextjs-hhfkzu?file=pages/index.js)

**Expected behavior**
The next app should run

**Screenshots**
<img width="803" alt="Screenshot 2022-07-29 at 7 09 26 PM" src="https://user-images.githubusercontent.com/59773847/181746961-24d90f8a-8896-48ef-a27d-05a457827f0d.png">

**Mexa SDK version (please complete the following information):**
 - Version: 3.0.1

**Additional context**
What I suspect is that because the v3 SDK is using `@biconomy/gasless-messaging-sdk` and `@biconomy/gasless-messaging-sdk` has dependencies that rely on core node modules such as `aqmplib`, therefore it does not work on client side. Since Nextjs 12 uses webpack 5 now and webpack 5 does not have these polyfills by default. I tried using nextjs12 with `node-polyfill-webpack-plugin` but it does not work as well.

**Comment by AmanRaj1608** [comment]
Hey, this can be resolved by using either using webpack 4 by downgrading the react-scripts to 4.0.3 

Or you can to configure webpack 5.
Can chec-out this issue and fix in PR.
https://github.com/bcnmy/gasless-playground/issues/2

https://github.com/bcnmy/gasless-playground/pull/1/files

More info 

- https://github.com/ChainSafe/web3.js#trouble-shooting-and-known-issues

- https://stackoverflow.com/a/64802753

**Comment by marcustut** [comment]
> Hey, this can be resolved by using either using webpack 4 by downgrading the react-scripts to 4.0.3 
> 
> Or you can to configure webpack 5.
> Can chec-out this issue and fix in PR.
> 
> - https://github.com/bcnmy/gasless-playground/issues/2
> 
> - https://github.com/bcnmy/gasless-playground/pull/1
> 
> More info 
> 
> - https://github.com/ChainSafe/web3.js#trouble-shooting-and-known-issues
> 
> - https://stackoverflow.com/a/64802753

However next.js 12 had deprecated webpack 4 support. So, there's no way to revert to webpack 4 for next.js users.

**Comment by AmanRaj1608** [comment]
Hey, you can still configure the webpack for all the packages required like fs, crypto...
I tried making changes in your [StackBlitz repo](https://stackblitz.com/edit/nextjs-g9whm3?file=next.config.js), it is working now

```bash
yarn add bufferutil net request tls utf-8-validate -D
```

Create `next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,

  webpack(config) {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      fs: false,
      bufferutil: require.resolve('bufferutil'),
      net: require.resolve('net'),
      request: require.resolve('request'),
      tls: require.resolve('tls'),
      'utf-8-validate': require.resolve('utf-8-validate'),
    };

    return config;
  },
};

module.exports = nextConfig;
```

Then update the Biconomy object inside useEffect as it is not a react hook.

**Comment by marcustut** [comment]
Thanks @AmanRaj1608 ! I can verified that it works now. However I'm facing an issue about `forwarder contract is undefined`. I took a look into the biconomy client object and the forwarder is empty.

**Comment by AmanRaj1608** [comment]
On which network are you trying @marcustut

**Comment by marcustut** [comment]
> On which network are you trying @marcustut

Polygon Mumbai

**Comment by marcustut** [comment]
<img width="597" alt="Screenshot 2022-08-02 at 4 01 10 PM" src="https://user-images.githubusercontent.com/59773847/182323745-b84011f0-0fc4-4e08-bbee-f79591c95d3c.png">

This is the exact error I'm getting. Whatever contracts or function I'm trying to call, it's throwing this error.

**Comment by Deveshb15** [comment]
Did you setup a trusted forwarder in your smart contract?

**Comment by livingrockrises** [comment]
closing this issue. for forwarder feel free to open another on discord dev support or get in touch on tg https://t.me/yashasvi_yc7
