### ISSUE TITLE
Only contractName is used to find out api information

### ISSUE THREAD

**Issue by sameepsi** [bcnmy/mexa-sdk#19]
SDK finds out the api information using only the methodName being executed. This is a blockcer for dapps which have multiple contracts in place and want to use native meta-transactions.

Steps to reproduce-:
1. Develop 2 contracts using native meta transactions guidelines
2. Add both of the contracts in the dashboard
3. Add API for executeMetaTransaction in the API of the dapp in dashboard. Select native meta tx at this step for both contracts
4. Now try to execute both contracts using mexa SDK

Result-:
One of the execution will definitely fail. As the sdk will pick up the apiId of the API added at the last.

https://github.com/bcnmy/mexa-sdk/blob/master/src/index.js#L550
Bug is at this line

**Comment by sameepsi** [comment]
Expected behaviour-:
API information should be fetched on the basis of following information-:
1. dapp used
2. Contract used
3. Method used

**Comment by tomarsachin2271** [comment]
This has been fixed in latest SDK version 1.5.6
