### ISSUE TITLE
Bits being inserted into uin256 parameters

### ISSUE THREAD

**Issue by Ethlings** [bcnmy/mexa-sdk#81]
**Describe the bug**
I have a function which takes in a uint256 value and performs some operations in the contract. The function has the following ABI:

{
      "inputs": [
        {
          "internalType": "uint256",
          "name": "id",
          "type": "uint256"
        }
      ],
      "name": "MY_FUNCTION",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
}

When the data is encoded in Biconomy, it adds random bytes into the middle of the string.

Here is the data it should be encoding:
0x1784800100000000000000000000000000000000000000000000000000000000

And here is what is being sent to Biconomy.
0x178480010000004becf851ccbbc0e9d00f695fdff66a42e0200000000000000000

I believe this is an issue with Biconomy trying to convert the number into scientific notation with this function:           
value = scientificToDecimal(paramObj.value);

This is 100% breaking and stops us from being able to call the contract with a single uint256 parameter.

**To Reproduce**
1. Create a function with a single uint256 parameter.
2. Call the function with a non-zero value (not sure if zero triggers it)
3. Emit the parameter from the contract function

The parameter will not be the same as what was passed from the javascript.

**Expected behavior**
This value should not be affected in any way.

**Screenshots**
![image](https://user-images.githubusercontent.com/81601221/119025235-c8ad6700-b958-11eb-9369-4e84751c9be4.png)

**Additional context**
This was verified by the Biconomy team.

**Comment by livingrockrises** [comment]
closing this issues as updated fix has been published couple of months ago.
